sonar.projectKey=platoformo
sonar.projectName=Platoformo Backend
sonar.scm.disabled=true

sonar.sources=src
sonar.tests=test

sonar.host.url=http://localhost:9000

sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/migrations/**