# Generated by Django 5.2.9 on 2026-08-18 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Name of the currency"
                    ),
                ),
                ("simbol", models.CharField(max_length=20, verbose_name="Simbol")),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "BILLING_CURRENCY",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("basic.agent.access", "Access to the agent type basic"),
                            ("medium.agent.access", "Acces to the agent type medium"),
                            (
                                "advanced.agent.access",
                                "Access to the agent type advance",
                            ),
                        ],
                        unique=True,
                        verbose_name="Code to identify the feature",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Name of the feature"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=100, verbose_name="Description of the feature"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "db_table": "BILLING_FEATURE",
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("TRIMESTER", "Trimester"),
                            ("ANNUAL", "Annual"),
                        ],
                        max_length=100,
                        verbose_name="The frequency",
                    ),
                ),
                (
                    "interval_count",
                    models.PositiveIntegerField(verbose_name="Number of months"),
                ),
            ],
            options={
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
                "db_table": "BILLING_PERIOD",
            },
        ),
        migrations.CreateModel(
            name="Quota",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("agent.chat.count", "The amount of chats with agents"),
                            ("basic.chat.count", "The amount of chats with users"),
                            ("group.chat.count", "The amount of groups"),
                            ("tokens.spend.monthly", "The money spend in tokens"),
                            (
                                "max.predictions.monthly",
                                "Max amount of users suggested",
                            ),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="Code of limiter",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Name of the feature"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=100, verbose_name="Description of the feature"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota",
                "verbose_name_plural": "Quotas",
                "db_table": "BILLING_QUOTA",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("MEMBER", "Member"),
                            ("PRO", "Pro"),
                            ("PREMIUM", "Premium"),
                        ],
                        max_length=100,
                        verbose_name="Plan name",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        null=True, unique=True, verbose_name="Stripe product"
                    ),
                ),
                ("features", models.ManyToManyField(to="Billing.feature")),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "db_table": "BILLING_PLAN",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "amount",
                    models.PositiveBigIntegerField(verbose_name="Amount on cents"),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        null=True, unique=True, verbose_name="Stripe price"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Billing.currency",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Billing.period"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Billing.plan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Price",
                "verbose_name_plural": "Prices",
                "db_table": "BILLING_PRICE",
            },
        ),
        migrations.CreateModel(
            name="QuotaPlan",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                ("limit", models.PositiveBigIntegerField(null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Billing.plan"
                    ),
                ),
                (
                    "quota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Billing.quota"
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota Plan",
                "verbose_name_plural": "Quotas Plans",
                "db_table": "BILLING_QUOTA_PLAN",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        null=True, unique=True, verbose_name="Stripe suscription id"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Final date"),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        verbose_name="Start date of the current period"
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(verbose_name="End date of the current period"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("CANCELED", "Canceled")],
                        max_length=100,
                        verbose_name="Status of the suscription",
                    ),
                ),
                (
                    "amount",
                    models.PositiveBigIntegerField(verbose_name="Amount on cents"),
                ),
                ("currency_code", models.CharField(max_length=3)),
                (
                    "plan_name",
                    models.CharField(max_length=100, verbose_name="Plan name"),
                ),
                (
                    "period_name",
                    models.CharField(max_length=100, verbose_name="Period name"),
                ),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Billing.price"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "BILLING_SUBSCRIPTION",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(verbose_name="Number of time apply"),
                ),
                (
                    "quota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Billing.quota"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Billing.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage",
                "verbose_name_plural": "Usages",
                "db_table": "BILLING_USAGE",
                "unique_together": {("quota", "subscription")},
            },
        ),
    ]
