# Generated by Django 5.2.9 on 2026-09-23 16:14

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Chat", "0002_contact"),
        ("MachineLearning", "0001_enable_vector"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAnalysis",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "sentiment",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Sentiment analysis from roBERTa",
                    ),
                ),
                (
                    "emotions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Emotions analysis of GoEmotions",
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Topic extraction from BERTopic",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True,
                        dimensions=384,
                        null=True,
                        verbose_name="Embedding from the text",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Chat.message"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Analysis",
                "verbose_name_plural": "Messages Analysis",
                "db_table": "MACHINE_LEARNING_MESSAGE_ANALYSIS",
            },
        ),
    ]
