# Generated by Django 5.2.9 on 2026-08-18 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        null=True,
                        verbose_name="Name of the group in case the chat have more than two participants",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        null=True,
                        verbose_name="Description of the gruop in case there is a group",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="group_avatar/"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="The time the chat was created"
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "db_table": "CHAT_CHAT",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Nature",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("analytical", "Analytical"),
                            ("creative", "Creative"),
                            ("empathetic", "Empathetic"),
                            ("logical", "Logical"),
                            ("intuitive", "Intuitive"),
                            ("patient", "Patient"),
                            ("energetic", "Energetic"),
                            ("calm", "Calm"),
                            ("assertive", "Assertive"),
                            ("collaborative", "Collaborative"),
                            ("independent", "Independent"),
                            ("detail_oriented", "Detail-oriented"),
                            ("visionary", "Visionary"),
                            ("pragmatic", "Pragmatic"),
                            ("adaptive", "Adaptive"),
                            ("principled", "Principled"),
                            ("curious", "Curious"),
                            ("decisive", "Decisive"),
                            ("reflective", "Reflective"),
                            ("proactive", "Proactive"),
                            ("supportive", "Supportive"),
                            ("critical_thinking", "Critical Thinker"),
                            ("communicative", "Communicative"),
                            ("reliable", "Reliable"),
                            ("innovative", "Innovative"),
                        ],
                        max_length=50,
                        verbose_name="Name of the nature",
                    ),
                ),
                (
                    "description",
                    models.CharField(verbose_name="Description of the nature"),
                ),
            ],
            options={
                "verbose_name": "Nature",
                "verbose_name_plural": "Nature",
                "db_table": "CHAT_NATURE",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("VIDEO", "Video"),
                            ("FILE", "File"),
                            ("IMAGE", "Image"),
                        ],
                        max_length=20,
                        verbose_name="Message type",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Content of the message"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Image attached",
                    ),
                ),
                (
                    "attach",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="File attached",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Video attached",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Time the message was created"
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Chat.chat"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "CHAT_MESSAGE",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "promp_type",
                    models.TextField(
                        verbose_name="Prompt that will be attach to the conversation"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description of the agent"),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("medium", "Medium"),
                            ("advance", "Advance"),
                        ],
                        max_length=20,
                        verbose_name="Type of agent",
                    ),
                ),
                ("natures", models.ManyToManyField(to="Chat.nature")),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "db_table": "CHAT_AGENT",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[("USER", "User"), ("AGENT", "AGENT")],
                        max_length=20,
                        verbose_name="Type of entity which is talking",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="last name"),
                ),
                ("nickname", models.CharField(max_length=150, verbose_name="Nickname")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="participant_avatar/"
                    ),
                ),
                (
                    "participant_status",
                    models.CharField(
                        choices=[
                            ("EN LINEA", "En linea"),
                            ("AUSENTE", "Ausente"),
                            ("NO MOLESTAR", "No molestar"),
                            ("INVISIBLE", "Invisible"),
                        ],
                        default="EN LINEA",
                        verbose_name="Status of the participant",
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Chat.agent",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
                "db_table": "CHAT_PARTICIPANT",
            },
        ),
        migrations.CreateModel(
            name="MessageStatus",
            fields=[
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_DELIVER", "Not yet deliver"),
                            ("DELIVER", "Delivar"),
                            ("READ", "Read"),
                        ],
                        default="DELIVER",
                        max_length=20,
                        verbose_name="Status of the message",
                    ),
                ),
                (
                    "upload_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Last update"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Chat.message"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Chat.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Status",
                "verbose_name_plural": "Message Statuses",
                "db_table": "CHAT_MESSAGE_STATUS",
            },
        ),
        migrations.AddField(
            model_name="message",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Chat.participant"
            ),
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Time the user/agent join the conversation",
                    ),
                ),
                (
                    "is_muted",
                    models.BooleanField(
                        default=False, verbose_name="Check if the user muted the chat"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        verbose_name="Check if the user is admin of a gruop",
                    ),
                ),
                (
                    "not_seen",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Number of messages not seen"
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Chat.chat"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Chat.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Participant",
                "verbose_name_plural": "Chat Participants",
                "db_table": "CHAT_CHAT_PARTICIPANT",
            },
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["agent_type"], name="CHAT_AGENT_agent_t_2be68f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("agent__isnull", True)),
                    models.Q(("user__isnull", True), ("agent__isnull", False)),
                    _connector="OR",
                ),
                name="participant_user_xor_agent",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_type"], name="CHAT_MESSAG_message_d88041_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together={("chat", "participant")},
        ),
    ]
