# Generated by Django 5.2.9 on 2026-08-31 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_of",
                        to="Chat.participant",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_contacts",
                        to="Chat.participant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacts",
                "verbose_name_plural": "Contacts",
                "db_table": "CHAT_CONTACT",
            },
        ),
    ]
