# Generated by Django 5.2.9 on 2026-08-18 16:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                (
                    "description",
                    models.CharField(blank=True, verbose_name="description"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "view"),
                            ("EDIT", "edit"),
                            ("DELETE", "delete"),
                        ],
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="priority")),
                ("effect", models.BooleanField(default=True)),
                (
                    "resource_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policy",
                "verbose_name_plural": "Policies",
                "db_table": "AUTHORIZATION_POLICY",
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Inactive"), (1, "Active")],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "activate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for an immediative activation",
                        null=True,
                    ),
                ),
                (
                    "deactivate_date",
                    models.DateField(
                        blank=True,
                        help_text="keep empty for indefinite activation",
                        null=True,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("user_attr", "User Attribute"),
                            ("resource_attr", "Resource Attribute"),
                            ("environment", "Environment"),
                            ("relationship", "Relationship"),
                        ],
                        max_length=20,
                        verbose_name="rule type",
                    ),
                ),
                (
                    "attribute_name",
                    models.CharField(max_length=100, verbose_name="attribute name"),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("equals", "Equals"),
                            ("not_equals", "Not Equals"),
                            ("contains", "Contains"),
                            ("in", "In"),
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("gte", "Greater Than or Equal"),
                            ("lte", "Less Than or Equal"),
                        ],
                        max_length=20,
                        verbose_name="operator",
                    ),
                ),
                ("value", models.CharField(max_length=200, verbose_name="value")),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="Authorization.policy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule",
                "verbose_name_plural": "Rules",
                "db_table": "AUTHORIZATION_RULE",
            },
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["resource_type"], name="AUTHORIZATI_resourc_4de8f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["policy"], name="AUTHORIZATI_policy__821b90_idx"
            ),
        ),
    ]
